/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.13
 * Generated at: 2023-10-06 14:24:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class AgregarUsuario_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1696545254283L));
    _jspx_dependants.put("/header.jsp", Long.valueOf(1696545254283L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width\", initial-scale=1,shrink-to-fit=no\">\n");
      out.write("    ");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css\"\n");
      out.write("	integrity=\"sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9\"\n");
      out.write("	crossorigin=\"anonymous\">\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-dark bg-dark\">\n");
      out.write("	<div class=\"container-fluid\">\n");
      out.write("		<button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarNavDarkDropdown\" aria-controls=\"navbarNavDarkDropdown\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n");
      out.write("			<span class=\"navbar-toggler-icon\"></span>\n");
      out.write("		</button>\n");
      out.write("		<div class=\"collapse navbar-collapse\" id=\"navbarNavDarkDropdown\">\n");
      out.write("			<ul class=\"navbar-nav\">\n");
      out.write("\n");
      out.write("				<li class=\"nav-item button\">\n");
      out.write("					<button class=\"btn btn-dark\" onclick=\"window.location.href='index.jsp'\">\n");
      out.write("						Inicio\n");
      out.write("					</button>\n");
      out.write("				</li>\n");
      out.write("\n");
      out.write("				<li class=\"nav-item dropdown\">\n");
      out.write("					<button class=\"btn btn-dark dropdown-toggle\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\n");
      out.write("						Altas\n");
      out.write("					</button>\n");
      out.write("					<ul class=\"dropdown-menu dropdown-menu-dark\">\n");
      out.write("						<li><a class=\"dropdown-item\" href=\"AgregarActividadDeportiva.jsp\">Actividad Deportiva</a></li>\n");
      out.write("						<li><a class=\"dropdown-item\" href=\"AgregarInstuticion.jsp\">Institucion Deportiva</a></li>\n");
      out.write("						<li><a class=\"dropdown-item\" href=\"AgregarUsuario.jsp\">Profesor/Socio</a></li>\n");
      out.write("						<li><a class=\"dropdown-item\" href=\"AltaDictadoClase.jsp\">Dictado de Clase</a></li>\n");
      out.write("					</ul>\n");
      out.write("				</li>\n");
      out.write("\n");
      out.write("				<li class=\"nav-item dropdown\">\n");
      out.write("					<button class=\"btn btn-dark dropdown-toggle\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\n");
      out.write("						Modificar\n");
      out.write("					</button>\n");
      out.write("					<ul class=\"dropdown-menu dropdown-menu-dark\">\n");
      out.write("						<li><a class=\"dropdown-item\" href=\"ModificarActividadDeportiva.jsp\">Actividad Deportiva</a></li>\n");
      out.write("						<li><a class=\"dropdown-item\" href=\"ModificarInstitucionDeportiva.jsp\">Institucion Deportiva</a></li>\n");
      out.write("						<li><a class=\"dropdown-item\" href=\"ModificarUsuario.jsp\">Usuario</a></li>\n");
      out.write("					</ul>\n");
      out.write("				</li>\n");
      out.write("\n");
      out.write("				<li class=\"nav-item dropdown\">\n");
      out.write("				<button class=\"btn btn-dark dropdown-toggle\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\n");
      out.write("					Consultas\n");
      out.write("				</button>\n");
      out.write("				<ul class=\"dropdown-menu dropdown-menu-dark\">\n");
      out.write("					<li><a class=\"dropdown-item\" href=\"ConsultaActividadDeportiva.jsp\">Actividad Deportiva</a></li>\n");
      out.write("					<li><a class=\"dropdown-item\" href=\"ConsultaUsuario.jsp\">Usuario</a></li>\n");
      out.write("					<li><a class=\"dropdown-item\" href=\"ConsultaDictadoClase.jsp\">Dictado de Clase</a></li>\n");
      out.write("					<li><a class=\"dropdown-item\" href=\"RankingClase.jsp\">Ranking de Clases</a></li>\n");
      out.write("				</ul>\n");
      out.write("				</li>\n");
      out.write("			</ul>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("</nav>\n");
      out.write("</body>\n");
      out.write("</html>");
      out.write("\n");
      out.write("    <title>Agregar Usuario</title>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("<form action=\"AgregarUsuario\" method=\"post\">\n");
      out.write("    <div class=\"form-group\">\n");
      out.write("        <label for=\"inputNickname\">Nickname</label>\n");
      out.write("        <input type=\"text\"\n");
      out.write("                name=\"nickname\"\n");
      out.write("                class=\"form-control\"\n");
      out.write("                id=\"inputNickname\"\n");
      out.write("                aria-describedby=\"emailHelp\"\n");
      out.write("                placeholder=\"Nickname de usuario\"\n");
      out.write("                value=\"\"\n");
      out.write("        >\n");
      out.write("    </div>\n");
      out.write("    <div class=\"form-group\">\n");
      out.write("        <label for=\"inputPassword\">Password</label> <input type=\"text\" name=\"password\"\n");
      out.write("                                                      class=\"form-control\" id=\"inputPasword\"\n");
      out.write("                                                      placeholder=\"Password de usuario\">\n");
      out.write("    </div>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"form-group\">\n");
      out.write("        <label for=\"inputEmail\">E-mail</label> <input type=\"text\" name=\"email\"\n");
      out.write("                                                                 class=\"form-control\" id=\"inputEmail\"\n");
      out.write("                                                                 placeholder=\"E-mail de usuario\">\n");
      out.write("    </div>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"form-group\">\n");
      out.write("        <label for=\"inputNombre\">Nombre</label> <input type=\"text\" name=\"nombre\"\n");
      out.write("                                                                 class=\"form-control\" id=\"inputNombre\"\n");
      out.write("                                                                 placeholder=\"Nombre de usuario\">\n");
      out.write("    </div>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"form-group\">\n");
      out.write("        <label for=\"inputFechaNacim\">Fecha de nacimiento</label> <input type=\"date\" name=\"fecNac\"\n");
      out.write("                                                                              class=\"form-control\" id=\"inputFechaNacim\"\n");
      out.write("                                                                              placeholder=\"Fecha de nacimiento de usuario\">\n");
      out.write("    </div>\n");
      out.write("    <div class=\"form-group\">\n");
      out.write("        <label for=\"tipoUsuario\">Tipo de Usuario</label>\n");
      out.write("        <select name=\"tipoUsuario\" id=\"tipoUsuario\" class=\"form-control\">\n");
      out.write("            <option value=\"\"selected disabled>Selecciona una opción</option>\n");
      out.write("            <option value=\"socio\">Socio</option>\n");
      out.write("            <option value=\"profesor\">Profesor</option>\n");
      out.write("        </select>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div id=\"camposProfesor\" style=\"display: none;\">\n");
      out.write("        <!-- Aquí puedes agregar los campos adicionales para el profesor -->\n");
      out.write("        <div class=\"form-group\">\n");
      out.write("            <label for=\"inputDesc\">Descripcion</label> <input type=\"text\" name=\"descripcion\"\n");
      out.write("                                                           class=\"form-control\" id=\"inputDesc\"\n");
      out.write("                                                           placeholder=\"Descripcion de profesor\"\n");
      out.write("                                                           value=\"\">\n");
      out.write("        </div>\n");
      out.write("        <div class=\"form-group\">\n");
      out.write("            <label for=\"inputBio\">Biografia</label> <input type=\"text\" name=\"biografia\"\n");
      out.write("                                                              class=\"form-control\" id=\"inputBio\"\n");
      out.write("                                                              placeholder=\"Biografia de profesor\">\n");
      out.write("        </div>\n");
      out.write("        <div class=\"form-group\">\n");
      out.write("            <label for=\"inputWeb\">Web</label> <input type=\"text\" name=\"web\"\n");
      out.write("                                                              class=\"form-control\" id=\"inputWeb\"\n");
      out.write("                                                              placeholder=\"Web del profesor\">\n");
      out.write("        </div>\n");
      out.write("        <div class=\"form-group\">\n");
      out.write("            <label for=\"inputInst\">Institucion</label> <input type=\"text\" name=\"institucion\"\n");
      out.write("                                                              class=\"form-control\" id=\"inputInst\"\n");
      out.write("                                                              placeholder=\"implementar instituciones disponibles\">\n");
      out.write("        </div>\n");
      out.write("        <!-- Agregar más campos según sea necesario para el profesor -->\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("    <!--SECCION DE SCRIPTS-->\n");
      out.write("    <script>\n");
      out.write("        document.getElementById(\"tipoUsuario\").addEventListener(\"change\", function () {\n");
      out.write("            var camposProfesor = document.getElementById(\"camposProfesor\");\n");
      out.write("            if (this.value === \"profesor\") {\n");
      out.write("                camposProfesor.style.display = \"block\"; // Mostrar campos adicionales\n");
      out.write("            } else {\n");
      out.write("                camposProfesor.style.display = \"none\"; // Ocultar campos adicionales\n");
      out.write("            }\n");
      out.write("        });\n");
      out.write("    </script>\n");
      out.write("    <script>\n");
      out.write("        // JavaScript para deseleccionar la opción al cargar la página\n");
      out.write("        document.addEventListener(\"DOMContentLoaded\", function () {\n");
      out.write("            var selectTipoUsuario = document.getElementById(\"tipoUsuario\");\n");
      out.write("            selectTipoUsuario.selectedIndex = -1; // Deseleccionar todas las opciones\n");
      out.write("        });\n");
      out.write("    </script>\n");
      out.write("\n");
      out.write("    <button type=\"submit\" class=\"btn btn-primary\">Agregar Socio</button>\n");
      out.write("</form>\n");
      out.write("\n");
      out.write("<script \n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js\"\n");
      out.write("	integrity=\"sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r\"\n");
      out.write("	crossorigin=\"anonymous\"></script>\n");
      out.write("<script\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.min.js\"\n");
      out.write("	integrity=\"sha384-Rx+T1VzGupg4BHQYs2gCW9It+akI2MM/mndMCy36UVfodzcJcF0GGLxZIzObiEfa\"\n");
      out.write("	crossorigin=\"anonymous\"></script>\n");
      out.write("<script\n");
      out.write("	src=\"https://code.jquery.com/jquery-3.7.1.slim.min.js\"\n");
      out.write("	integrity=\"sha256-kmHvs0B+OpCW5GVHUNjv9rOmY0IvSIRcf7zGUDTDQM8=\"\n");
      out.write("	crossorigin=\"anonymous\"></script>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("</body>");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
